### ISSUE TITLE
Plugin fails to parse the trajectory of BAND calculations

### ISSUE THREAD

**Issue by edditler** [cp2k/aiida-cp2k#9]
The CP2K plugin is looking for `aiida-1.restart` in order to parse the coordinates from it by the scheme `X 1 2 3\newline`:
https://github.com/cp2k/aiida-cp2k/blob/master/aiida_cp2k/parsers/__init__.py#L91
`m_apattern = '(\w+)\s+([\d\.+-E]+)\s+([\d\.+-E]+)\s+([\d\.+-E]+)'`.

The `aiida-1.restart` for BAND calculations looks like
```
     &REPLICA
       &COORD
             1   2   3
              ...
       &END COORD
       &VELOCITY
             1   2   3
              ...
       &END VELOCITY
     &END REPLICA
     &REPLICA
          ...
```

Because the atomic kind is missing the parser fails with an exception. Further parsing only one geometry out of all replicas does not make sense.

The question is: should the parser recognize the BAND calculation from the `   RUN_TYPE  BAND` line and parse all replicas or should the exception be caught and no trajectory parsed at all.

Error traceback:
```
03/17/2018 08:36:37 PM, aiida.execmanager: [ERROR] Error parsing calc 52956. Traceback: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aiida/daemon/execmanager.py", line 787, in retrieve_computed_for_authinfo
    successful, new_nodes_tuple = parser.parse_from_calc(retrieved_temporary_folder)
  File "/usr/local/lib/python2.7/dist-packages/aiida/parsers/parser.py", line 81, in parse_from_calc
    return self.parse_with_retrieved(retrieved)
  File "/usr/local/lib/python2.7/dist-packages/aiida_cp2k/parsers/__init__.py", line 47, in parse_with_retrieved
    self._parse_trajectory(out_folder, new_nodes_list)
  File "/usr/local/lib/python2.7/dist-packages/aiida_cp2k/parsers/__init__.py", line 95, in _parse_trajectory
    atoms += Atom(a[0], (a[1:]))
  File "/usr/local/lib/python2.7/dist-packages/ase/atom.py", line 92, in __init__
    d['number'] = atomic_numbers[symbol]
KeyError: '01'
```

**Comment by oschuett** [comment]
I would like to stick to the original philosophy of keeping the aiida-cp2k plugin as lightweight (and robust) as possible. Hence, we should simply catch the exception and not return an output_structure in that case. Could you prepare a PR?

**Comment by edditler** [comment]
The travis build for https://github.com/cp2k/aiida-cp2k/pull/10 is failing (at least in my repo) at

```
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends     build-essential           python-setuptools         python-wheel              python-pip                python-dev                postgresql                less                      nano                      sudo                      ssh                       cp2k                    && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
The command "docker build -t aiida_cp2k_test ." failed and exited with 100 during .
```

**Comment by oschuett** [comment]
Thank for figuring this out :-)
